name: Frontend Review

on:
  push:
    paths:
      - "frontend/**"
      - ".github/workflows/frontend-review.yml"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    name: Frontend Review
    defaults:
      run:
        working-directory: ./frontend
    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js v16.13.1
        uses: actions/setup-node@v3
        with:
          node-version: 16.13.1
      - name: Install Node Packages
        run: |
          cd frontend
          npm install
      - name: Run Jest
        run: |
          cd frontend
          npm test
      - name: Publish Test Results
        uses: EnricoMi/publish-unit-test-result-action/composite@v2
        if: always()
        with:
          junit_files: "frontend/junit.xml"
      - name: Upload Artifect
        uses: actions/upload-artifact@v3
        if: always()
        with:
          name: frontend_test_report
          path: frontend/junit.xml
